# Generated by Django 5.0.1 on 2024-01-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundkit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundkit',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='soundkit',
            name='image',
            field=models.ImageField(default='soundkit_covers/default.jpg', upload_to='soundkit_covers/'),
        ),
        migrations.AddField(
            model_name='soundkit',
            name='sound_file',
            field=models.FileField(default='soundkits/default_sound.mp3', upload_to='soundkits/'),
        ),
        migrations.AlterField(
            model_name='soundkit',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
