# Generated by Django 5.0.1 on 2024-02-18 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundkit', '0002_soundkit_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundkit',
            name='zip_file',
            field=models.FileField(default='placeholder.zip', upload_to='soundkit_zips/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
            preserve_default=False,
        ),
    ]
