# Generated by Django 5.0.1 on 2024-02-18 22:42

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundkit', '0003_alter_soundkit_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundkit',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='soundkit',
            name='sound_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='sound'),
        ),
        migrations.AlterField(
            model_name='soundkit',
            name='zip_file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='zip'),
        ),
    ]
