# Generated by Django 5.0.1 on 2024-02-19 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundkit', '0004_alter_soundkit_image_alter_soundkit_sound_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundkit',
            name='sound_file',
        ),
        migrations.AlterField(
            model_name='soundkit',
            name='image',
            field=models.ImageField(upload_to='soundkits/images/'),
        ),
        migrations.AlterField(
            model_name='soundkit',
            name='zip_file',
            field=models.FileField(upload_to='soundkits/zips/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
    ]
